name: javascript_env
channels:
  - conda-forge
  - defaults
dependencies:
  - nodejs
#---------------------------------------------------------------------------------------------------------------------------------------------
  #- 
